### ISSUE TITLE
Trouble using scil_compute_pft_maps_from_civet.py with singularity container

### ISSUE THREAD

**Issue by sidchop** [scilus/tractoflow-pve#2]
Hi,

Thanks for making this modification for tractoflow. I really like tractoflow, but found the FAST segmentation of the subcortex very poor in my data, so this version is ideal. I am having some trouble getting the nextflow pipeline working with the singularity image. After adding `singularity.autoMounts = true` to the nextflow.config file, the pipeline works fine until the PFT map generation, where it is unable to access the scil_compute_pft_maps_from_civet.py in the /bin folder. I am guessing this is because using the singularity container with nf overrides the access to the /bin folder where the script is located? 

I have also tried manually specifying the path to the /bin foder, but had no luck:

`singularity.runOptions="--bind /path/to/tractoflow_root/,path/to/nf,path/to/tractoflow-pve/bin/"`

Here is my command to call tractoflow:

`module load singularity
nextflow -C /tractoflow-pve/nextflow.config run tractoflow-pve/main.nf --root /data/tractoflow_root/ --dti_shells "0 3000" --fodf_shells "0 3000" --run_dwi_denoising "false" --run_topup "false" -profile civet_pve --algo "prob"  -with-report report.html --run_eddy "false" --nbr_seeds 15 --wm_seeding false -with-singularity tractoflow_2.0.0_8b39aee_2019-04-26.img `

Any advice here would be greatly appreciated, and thanks again for making this pipeline.

**Comment by jchoude** [comment]
Hi @sidchop 

Thanks for your interest!

1) Could you provide us with the full error log as an attached file? 

2) If you still have your work directory, could you send us the content of `.command.sh` and `.command.err`? If you can find the ID of the process that failed (will normally look like `XX/XXXXX`), you can go in the subdirectory `work/XX/XXXXX`, and the 2 requested files are there as hidden files.

3) As a sidenote, using b=3000 for your DTI shell is not recommended.

Best,

**Comment by sidchop** [comment]
Thanks for the quick response! 

1. Please find attached the full error log (I have just run one subject for ease):
[nextflow.log](https://github.com/scilus/tractoflow-pve/files/5890650/nextflow.log)

2. The output of the .command.sh file is: 
`scil_compute_pft_maps_from_civet.py sub-001__pve_wm_bet_cropped_resampled_warped.nii.gz sub-001__pve_gm_bet_cropped_resampled_warped.nii.gz sub-001__pve_csf_bet_cropped_resampled_warped.nii.gz sub-001__pve_sc_bet_cropped_resampled_warped.nii.gz        --include sub-001__map_include.nii.gz        --exclude sub-001__map_exclude.nii.gz        --interface sub-001__interface.nii.gz        --sc_include_val 0.2`

and the .command.err:
`/projects/kg98/Sid/STAGES/STAGES_dti/scripts/TractoFlow_pve2/work/23/27af63e9ad525d6978185248f6fb6a/.command.sh: line 2: scil_compute_pft_maps_from_civet.py: command not found`

Here is my directory tree: 
![image](https://user-images.githubusercontent.com/27250072/106212982-ddd27e80-621f-11eb-833f-e35fabac087a.png)

3. In terms of the DTI shells, the data we acquired was single shell (b=3000). Although, our end goal here is to derive whole-brain structural connectivity matrices (not weighted by dti metrics).

Thanks!

**Comment by StongeEtienne** [comment]
Hi, I never used the "singularity.autoMounts = true", so maybe it's link to this.
Maybe double check that the script "scil_compute_pft_maps_from_civet.py" is executable (chmod +x).
If this is not the error, maybe @jchoude have a better idea.

**Comment by sidchop** [comment]
If I remove `singularity.autoMounts = true` from the nextflow.config file, the pipeline fails all steps as i think its unable to access the root dir. log:
[nextflow2.log](https://github.com/scilus/tractoflow-pve/files/5890965/nextflow2.log)

 .command.sh example: 
`#!/bin/bash -ue
mv t1.nii.gz sub-001__t1_denoised.nii.gz`

 .command.log example: 
`nxf-scratch-dir m3c001:/tmp/nxf.R77WuJfBSI
/bin/bash: /projects/kg98/Sid/STAGES/STAGES_dti/scripts/TractoFlow_pve2/work/d4/ecbdb20ac7250fb5b97189a97cf621/.command.run: No such file or directory
cp: cannot stat \u2018.command.trace\u2019: No such file or directory`

Can also confirm that the file is executable (at least outside the container).

**Comment by GuillaumeTh** [comment]
Hi @sidchop,

You must to add `singularity.autoMounts = true` in the nextflow.config file. As you said, this option will mount automatically everything in the container. As you did for .command.err, can you give me your .command.run.

Best

**Comment by sidchop** [comment]
Hi @GuillaumeTh ,

Here is the `.command.run` (after ive added `singularity.autoMounts = true` back in): [nextflowrun.txt](https://github.com/scilus/tractoflow-pve/files/5896641/nextflowrun.txt)

Thanks,
Sid

**Comment by GuillaumeTh** [comment]
Thanks @sidchop,

Everything looks ok. Can you try the following command adding `singularity.autoMounts = true` in the nextflow.config file:

module load singularity nextflow run tractoflow-pve/main.nf --root /data/tractoflow_root/ --dti_shells "0 3000" --fodf_shells "0 3000" --run_dwi_denoising "false" --run_topup "false" -profile civet_pve --algo "prob" -with-report report.html --run_eddy "false" --nbr_seeds 15 --wm_seeding false -with-singularity tractoflow_2.0.0_8b39aee_2019-04-26.img

If it crash, can you send me the .command.err, .command.sh, .command.run

Thanks

Guillaume

**Comment by sidchop** [comment]
Thanks, @GuillaumeTh - I figured out the issue. My tractoflow_root was not in my main project folder. Moving the data into my analysis folder fixed this issue. 

However, I am now running into a different problem. Looking like in tractoflow-pve, the default for the --random is a vector. (random=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]). I do not require this, and when I try to change the default, the pipline crashes stright away (if I dont include the --random flag, and run with the default - the pipeline runs fine): 

`nextflow run tractoflow-pve/main.nf --root data/tractoflow_root/ --dti_shells "0 3000" --fodf_shells "0 3000" --run_dwi_denoising "false" --run_topup "false" -profile civet_pve --algo "prob" -with-report report.html --run_eddy "false" --nbr_seeds 15 --seeding npv --wm_seeding false --random 0   --mean-frf true -with-singularity tractoflow_2.0.0_8b39aee_2019-04-26.img`

The nextflow.log: [nf_log.txt](https://github.com/scilus/tractoflow-pve/files/5908310/nf_log.txt)
.command.err is empty
.command.log: `nxf-scratch-dir m3c008:/tmp/nxf.fJywHFs5hk`
.commang.sh: `#!/bin/bash -ue
mv dwi.nii.gz sub-001__dwi_denoised.nii.gz`

I tried changing the defaults in the nextflow.config to `random=0`, but the pipeline still crashes. 

Thanks a lot for your help with this.

**Comment by StongeEtienne** [comment]
@sidchop the radom seed  list is required, and is used to parallelize the tracking process.

To have a reproducible tracking, this seed is also required, and sadly I used a list.
I personally recommend to keep de default to multhread the tracking (with --seeding nt}.
However, if you do not want that behavior, put random=[1] direcly in the config file.

**Comment by sidchop** [comment]
@StongeEtienne ah, I see - parallelize the tracking process is indeed useful. Thanks for all your help guys! 

Ps, if I wanted to merge the resulting tractograms from a parallelized run into a single .trk, would you know how best to do that?

**Comment by StongeEtienne** [comment]
you can use a scilpy script on resulting trk,
`singularity exec tractoflow2.0.img scil_streamline_math.py concatenate *.trk   all.trk`

**Comment by sidchop** [comment]
Great, thanks!
